apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 420122552625.dkr.ecr.ap-southeast-1.amazonaws.com/simplebank:0d2a0da21e90d8e38f48ce3677430eb53f16c63d
        imagePullPolicy: Always
        ports:
        - containerPort: 8080